base_config: ldf_base.yaml

dirs:
  deps: /data/home/shengqiuProf_user_yuankai/FloodDiffusion/deps
  outputs: /data/home/shengqiuProf_user_yuankai/FloodDiffusion/outputs
  raw_data: /data/home/shengqiuProf_user_yuankai/FloodDiffusion/raw_data

save_dir: ./outputs/ldf

trainer:
  devices: 8

validation:
  t2m:
    enabled: true

vae:
  checkpoint_path: null

data:
  target: datasets.humanml3d.HumanML3DDataset
  text_embeddings_path: ${dirs.raw_data}/HumanML3D_motion_local/t5_text_embeddings.pt
  text_meta_paths:
    - ${dirs.raw_data}/HumanML3D_motion_local/all.txt
  train_meta_paths:
    - ${dirs.raw_data}/HumanML3D_motion_local/train.txt
  val_meta_paths:
    - ${dirs.raw_data}/HumanML3D_motion_local/val.txt
  test_probe_meta_paths:
    dense_xz:
      - ${dirs.raw_data}/HumanML3D_motion_local/test.txt
  artifact_path: artifacts
  text_path: texts
  train_batch_size: 32
  val_batch_size: 32
  num_workers: 2
