base_config: ldf_base.yaml

exp_name: ldf_hybrid_humanml3d_babel
save_dir: /data1/yuankai/text2Motion/Floodcontrol/ldf

trainer:
  devices: 1

validation:
  generation:
    enabled: false
  dense_xz:
    enabled: false
  t2m:
    enabled: false

vae:
  checkpoint_path: /data1/yuankai/text2Motion/Floodcontrol/vae/20260715_164325_vae_body265/last.ckpt
  params:
    latent_stats_path: /data1/yuankai/text2Motion/Floodcontrol/vae/20260715_164325_vae_body265/latent_stats.npz

data:
  target: datasets.multi.MultiDataset
  text_embeddings_path: ${dirs.raw_data}/HumanML3D_BABEL_t5_text_embeddings.pt
  datasets:
    - target: datasets.humanml3d.HumanML3DDataset
      text_meta_paths:
        - ${dirs.raw_data}/HumanML3D_motion/all.txt
      train_meta_paths:
        - ${dirs.raw_data}/HumanML3D_motion/train.txt
      val_meta_paths:
        - ${dirs.raw_data}/HumanML3D_motion/val.txt
      artifact_path: artifacts
      text_path: texts
    - target: datasets.babel.BABELDataset
      text_meta_paths:
        - ${dirs.raw_data}/BABEL_motion/all.txt
      train_meta_paths:
        - ${dirs.raw_data}/BABEL_motion/train.txt
      val_meta_paths:
        - ${dirs.raw_data}/BABEL_motion/val.txt
      artifact_path: artifacts
      text_path: texts
  train_batch_size: 16
  val_batch_size: 16
  num_workers: 16
