base_config: ldf_base.yaml

dirs:
  deps: /data1/yuankai/text2Motion/FloodDiffusion/deps
  outputs: /data1/yuankai/text2Motion/FloodDiffusion/outputs
  raw_data: /data1/yuankai/text2Motion/FloodDiffusion/raw_data

save_dir: /data1/yuankai/text2Motion/Floodcontrol/ldf

trainer:
  devices: 1

validation:
  t2m:
    enabled: false

vae:
  checkpoint_path: null

data:
  target: datasets.humanml3d.HumanML3DDataset
  text_embeddings_path: ${dirs.raw_data}/HumanML3D_motion_local/t5_text_embeddings.pt
  text_meta_paths:
    - ${dirs.raw_data}/HumanML3D_motion_local/all.txt
  train_meta_paths:
    - ${dirs.raw_data}/HumanML3D_motion_local/train.txt
  val_meta_paths:
    - ${dirs.raw_data}/HumanML3D_motion_local/val.txt
  test_probe_meta_paths:
    dense_xz:
      - ${dirs.raw_data}/HumanML3D_motion_local/test.txt
  artifact_path: artifacts
  text_path: texts
  train_batch_size: 8
  val_batch_size: 16
  num_workers: 16
