dirs:
    deps: "/data1/yuankai/text2Motion/FloodDiffusion/deps"
    outputs: "/data1/yuankai/text2Motion/FloodDiffusion/outputs"
    raw_data: "/data1/yuankai/text2Motion/FloodDiffusion/raw_data"

wandb_info:
    key: "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"
    entity: "laiyuankia-nanjing-university"
